# Generated by Django 5.0.7 on 2024-08-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proaccount",
            name="onboarding_completed",
        ),
        migrations.AddField(
            model_name="proaccount",
            name="business_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="proaccount",
            name="languages",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proaccount",
            name="profile_visibility",
            field=models.BooleanField(default=True),
        ),
    ]
