# Generated by Django 5.0.6 on 2024-07-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp",
            "0002_service_myuser_is_pro_myuser_pro_account_created_at_and_more",
        ),
    ]

    operations = []
