# Generated by Django 5.0.7 on 2024-08-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_proaccount_onboarding_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proaccount",
            name="availability",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="proaccount",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="proaccount",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="proaccount",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="proaccount",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
