# Generated by Django 5.0.6 on 2024-07-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_auto_20240719_0243"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_photos/"
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
