# Generated by Django 5.0.6 on 2024-07-19 15:10
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_myuser_bio_myuser_profile_picture_delete_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="profile_picture",
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "myapp_userprofile",
            },
        ),
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS pro_account;",
                "DROP TABLE IF EXISTS service;",
                "DROP TABLE IF EXISTS user_profile;",
                "DROP TABLE IF EXISTS user_service;",
            ],
            reverse_sql=["SELECT 1;"],  # Do nothing in reverse
        ),
    ]
