# Generated by Django 5.0.6 on 2024-07-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_final_cleanup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="is_admin",
        ),
    ]
