# Generated by Django 5.0.6 on 2024-07-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_myuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="proaccount",
            name="availability",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="proaccount",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="proaccount",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="proaccount",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pics/"
            ),
        ),
        migrations.AddField(
            model_name="proaccount",
            name="rates",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
