# Generated by Django 5.0.6 on 2024-07-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_proaccount_availability_proaccount_bio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZipCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("city", models.CharField(max_length=255)),
            ],
        ),
    ]
