# Generated by Django 5.0.6 on 2024-07-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_zipcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zipcode",
            name="city",
        ),
        migrations.AlterModelTable(
            name="zipcode",
            table="myapp_zipcodes",
        ),
    ]
