# Generated by Django 5.0.6 on 2024-07-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_remove_zipcode_city_alter_zipcode_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proaccount",
            name="rates",
            field=models.TextField(blank=True, null=True),
        ),
    ]
