# Generated by Django 5.0.6 on 2024-07-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_proaccount_rates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proaccount",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="proaccount",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="proaccount",
            name="become_a_pro_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proaccount",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
