# Generated by Django 5.0.6 on 2024-07-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_remove_proaccount_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proaccount",
            name="availability",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
