# Generated by Django 5.0.6 on 2024-07-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_proaccount_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proaccount",
            name="availability",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
