# Generated by Django 5.0.6 on 2024-07-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_alter_proaccount_availability"),
    ]

    operations = []
