# Generated by Django 5.0.6 on 2024-07-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_auto_20240721_1536"),
        ("myapp", "0017_add_is_pro_field"),
    ]

    operations = []
